"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { TrendingUp, ThumbsUp, ThumbsDown, Edit3, CheckCircle2 } from "lucide-react";

interface Recommendation {
  id: number;
  parameter: string;
  displayName: string;
  current: number;
  recommended: number;
  change: number;
  unit: string;
  importance: number;
  explanation: string;
  status: "pending" | "accepted" | "rejected" | "modified";
}

const initialRecommendations: Recommendation[] = [
  {
    id: 1,
    parameter: "machine_speed",
    displayName: "Machine Speed",
    current: 785,
    recommended: 762,
    change: -23,
    unit: "m/min",
    importance: 0.284,
    explanation: "Decrease machine speed allows more fiber deposition per unit area, increasing GSM toward target.",
    status: "pending",
  },
  {
    id: 2,
    parameter: "dryer_temperature",
    displayName: "Dryer Temperature",
    current: 128.4,
    recommended: 124.0,
    change: -4.4,
    unit: "°C",
    importance: 0.218,
    explanation: "Lower dryer temperature retains more moisture, increasing final GSM.",
    status: "pending",
  },
  {
    id: 3,
    parameter: "headbox_pressure",
    displayName: "Headbox Pressure",
    current: 2.65,
    recommended: 2.70,
    change: 0.05,
    unit: "bar",
    importance: 0.176,
    explanation: "Increase headbox pressure to improve fiber distribution, raising GSM.",
    status: "pending",
  },
  {
    id: 4,
    parameter: "moisture_content",
    displayName: "Moisture Content",
    current: 5.2,
    recommended: 5.6,
    change: 0.4,
    unit: "%",
    importance: 0.152,
    explanation: "Higher moisture content increases paper weight, raising GSM.",
    status: "pending",
  },
];

export default function RecommendationsPage() {
  const [recommendations, setRecommendations] = useState(initialRecommendations);

  const handleAction = (id: number, action: "accepted" | "rejected") => {
    setRecommendations((prev) =>
      prev.map((r) => (r.id === id ? { ...r, status: action } : r))
    );
  };

  const accepted = recommendations.filter((r) => r.status === "accepted").length;
  const rejected = recommendations.filter((r) => r.status === "rejected").length;
  const pending = recommendations.filter((r) => r.status === "pending").length;

  const expectedGSM = 120 - 0.35 - 0.22 + 0.12 + 0.08;

  return (
    <div className="space-y-8 animate-in">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Recommendation Center</h1>
          <p className="text-muted-foreground mt-1">
            Optimal machine settings generated by AI — review and act
          </p>
        </div>
        <div className="flex gap-4">
          <div className="text-center">
            <span className="text-xs text-muted-foreground block">Expected GSM</span>
            <span className="text-xl font-bold text-emerald-400">{expectedGSM.toFixed(1)}</span>
          </div>
          <div className="text-center">
            <span className="text-xs text-muted-foreground block">Improvement</span>
            <span className="text-xl font-bold text-blue-400">+1.1 GSM</span>
          </div>
        </div>
      </div>

      {/* Summary Bar */}
      <div className="flex gap-4">
        <div className="flex-1 glass-card !py-3 text-center">
          <span className="text-2xl font-bold text-blue-400">{pending}</span>
          <span className="text-xs text-muted-foreground block">Pending</span>
        </div>
        <div className="flex-1 glass-card !py-3 text-center">
          <span className="text-2xl font-bold text-emerald-400">{accepted}</span>
          <span className="text-xs text-muted-foreground block">Accepted</span>
        </div>
        <div className="flex-1 glass-card !py-3 text-center">
          <span className="text-2xl font-bold text-red-400">{rejected}</span>
          <span className="text-xs text-muted-foreground block">Rejected</span>
        </div>
      </div>

      {/* Recommendations */}
      <div className="space-y-4">
        {recommendations.map((rec, i) => (
          <motion.div
            key={rec.id}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.1 }}
            className={`glass-card border-l-4 ${
              rec.status === "accepted"
                ? "border-emerald-500"
                : rec.status === "rejected"
                ? "border-red-500"
                : "border-blue-500"
            }`}
          >
            <div className="flex items-start justify-between">
              <div className="flex-1">
                <div className="flex items-center gap-3 mb-2">
                  <h3 className="font-semibold">{rec.displayName}</h3>
                  <span className={`text-xs px-2 py-0.5 rounded-full ${
                    rec.status === "accepted"
                      ? "bg-emerald-500/20 text-emerald-400"
                      : rec.status === "rejected"
                      ? "bg-red-500/20 text-red-400"
                      : "bg-blue-500/20 text-blue-400"
                  }`}>
                    {rec.status.toUpperCase()}
                  </span>
                  <span className="text-xs text-muted-foreground">
                    Importance: {(rec.importance * 100).toFixed(1)}%
                  </span>
                </div>

                <div className="flex items-center gap-6 mb-3">
                  <div className="text-center">
                    <span className="text-xs text-muted-foreground block">Current</span>
                    <span className="font-mono font-bold">{rec.current} {rec.unit}</span>
                  </div>
                  <div className="text-muted-foreground">→</div>
                  <div className="text-center">
                    <span className="text-xs text-muted-foreground block">Recommended</span>
                    <span className="font-mono font-bold text-emerald-400">{rec.recommended} {rec.unit}</span>
                  </div>
                  <div className="text-center">
                    <span className="text-xs text-muted-foreground block">Change</span>
                    <span className={`font-mono font-bold ${rec.change < 0 ? "text-red-400" : "text-emerald-400"}`}>
                      {rec.change > 0 ? "+" : ""}{rec.change} {rec.unit}
                    </span>
                  </div>
                </div>

                <p className="text-sm text-muted-foreground">{rec.explanation}</p>
              </div>

              {rec.status === "pending" && (
                <div className="flex gap-2 ml-4">
                  <button
                    onClick={() => handleAction(rec.id, "accepted")}
                    className="p-2 rounded-lg bg-emerald-500/20 text-emerald-400 hover:bg-emerald-500/30 transition-colors"
                  >
                    <ThumbsUp className="w-4 h-4" />
                  </button>
                  <button
                    onClick={() => handleAction(rec.id, "rejected")}
                    className="p-2 rounded-lg bg-red-500/20 text-red-400 hover:bg-red-500/30 transition-colors"
                  >
                    <ThumbsDown className="w-4 h-4" />
                  </button>
                  <button className="p-2 rounded-lg bg-blue-500/20 text-blue-400 hover:bg-blue-500/30 transition-colors">
                    <Edit3 className="w-4 h-4" />
                  </button>
                </div>
              )}
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
